/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Stage } from "./Stage";
import { StageCountArgs } from "./StageCountArgs";
import { StageFindManyArgs } from "./StageFindManyArgs";
import { StageFindUniqueArgs } from "./StageFindUniqueArgs";
import { CreateStageArgs } from "./CreateStageArgs";
import { UpdateStageArgs } from "./UpdateStageArgs";
import { DeleteStageArgs } from "./DeleteStageArgs";
import { StageService } from "../stage.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Stage)
export class StageResolverBase {
  constructor(
    protected readonly service: StageService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Stage",
    action: "read",
    possession: "any",
  })
  async _stagesMeta(
    @graphql.Args() args: StageCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Stage])
  @nestAccessControl.UseRoles({
    resource: "Stage",
    action: "read",
    possession: "any",
  })
  async stages(@graphql.Args() args: StageFindManyArgs): Promise<Stage[]> {
    return this.service.stages(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Stage, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Stage",
    action: "read",
    possession: "own",
  })
  async stage(
    @graphql.Args() args: StageFindUniqueArgs
  ): Promise<Stage | null> {
    const result = await this.service.stage(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Stage)
  @nestAccessControl.UseRoles({
    resource: "Stage",
    action: "create",
    possession: "any",
  })
  async createStage(@graphql.Args() args: CreateStageArgs): Promise<Stage> {
    return await this.service.createStage({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Stage)
  @nestAccessControl.UseRoles({
    resource: "Stage",
    action: "update",
    possession: "any",
  })
  async updateStage(
    @graphql.Args() args: UpdateStageArgs
  ): Promise<Stage | null> {
    try {
      return await this.service.updateStage({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Stage)
  @nestAccessControl.UseRoles({
    resource: "Stage",
    action: "delete",
    possession: "any",
  })
  async deleteStage(
    @graphql.Args() args: DeleteStageArgs
  ): Promise<Stage | null> {
    try {
      return await this.service.deleteStage(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
